### ISSUE TITLE
tanya pak

### ISSUE THREAD

**Issue by azkara** [didikw/zte_c320_monitoring#4]
kenapa munculnya gini ya
 Error in plugin: agent udp://IP:161: performing get on field hostname: request timeout

**Comment by didikw** [comment]
Pastikan port UDP 161 tidak tertutup Pak di sisi penerima bisa dicoba dengan nc -vz -u [host] 161 atau cek ufw status jika menggunakan UFW

**Comment by azkara** [comment]
oke sudah bisa dengan cara allow port pada ufw pak, namun kemudian muncul begini
[inputs.snmp] Collection took longer than expected; not complete after interval of 10s
